---
title: "CodeBook"
author: "Anat Nusinovich"
date: "30/05/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The run_analysis.R script includes the following steps: 

1. Downloading the dataset- the dataset is downloaded and extracted under the folder called UCI HAR Dataset.

2. Assigning each data to variables- 
features <- features.txt : 561 rows, 2 columns
activities <- activity_labels.txt : 6 rows, 2 columns
subject_test <- test/subject_test.txt : 2947 rows, 1 column
x_test <- test/X_test.txt : 2947 rows, 561 columns
y_test <- test/y_test.txt : 2947 rows, 1 columns
subject_train <- test/subject_train.txt : 7352 rows, 1 column
x_train <- test/X_train.txt : 7352 rows, 561 columns
y_train <- test/y_train.txt : 7352 rows, 1 columns

3. Merging the training and the test sets to create one data set- 
X (10299 rows, 561 columns) is created by merging x_train and x_test using rbind() function
Y (10299 rows, 1 column) is created by merging y_train and y_test using rbind() function
Subject (10299 rows, 1 column) is created by merging subject_train and subject_test using rbind() function
Merged_Data (10299 rows, 563 column) is created by merging Subject, Y and X using cbind() function

4. Extracting only the measurements on the mean and standard deviation for each measurement- 
The set TidyData is created by subsetting Merged_Data and selecting only the following columns: subject, code, measurements on the mean, and standard deviation for each measurement.

5. Using descriptive activity names to name the activities in the data set- 
Numbers in the code column in TidyData are replaced with the corresponding activity taken from the second column of the activities variable. 

6. Appropriately naming the data set with descriptive variable names- 
code (TidyData) = activities 
Acc = Accelerometer 
Gyro = Gyroscope 
BodyBody = Body 
Mag = Magnitude 
f = Frequency 
t = Time

7. Creating a second, independent tidy data set with the average of each variable for each activity and each subject- 
The set FinalData is created from a summary of TidyData. The summary takes the mean of each activity and each subject after grouping. FinalData is then exported to FinalData.txt file. 


